### PR TITLE
Feature/search results

### PR DESCRIPTION
**Pull request by zachcygan**
I began the page construction of the search results. It contains the first search results from an api search that contains a picture as well as the title.

### CODE REVIEW

**Review by MonaMLii — COMMENTED** [review]
looks great!

**Review by MonaMLii — COMMENTED** [review]
no conflict

**Review by MonaMLii — DISMISSED** [review]
no confilct

**Review by lapuzshawn — DISMISSED** [review]
no conflicts

**Review by lapuzshawn — APPROVED** [review]

**Review by ltram16 — APPROVED** [review]

**Pull request merged**
